### ISSUE TITLE
CPU temperature module problem

### ISSUE THREAD

**Issue by ArtemChandragupta** [thelazt16/dotfiles#1]
Hello. I am learning ags by rewriting my waybar config with it:
![image](https://github.com/user-attachments/assets/7e97455a-6171-4cf1-92e1-c15acfeeb31c)

As you can see, I have a block with CPU and RAM usage and CPU temperature. I am not competent enough to write my own services for pulling this values (because I have no idea how bash works), so I looking for other ags confings that utilizes this.

So, I copied your modules responding for that. CPU and memory usage is great (for some reason, on NixOS many other people scripts don't have permission for pulling cpu and memory information, I can't figure out why), but CPU temperature is NaN:
![image](https://github.com/user-attachments/assets/c8485b7e-aaee-44e9-9e98-e12223c08a0e)

Do you have any Ideas why is this happening and how I can fix this?

**Comment by ArtemChandragupta** [comment]
Issue is resolved - I have not lm-sensors installed on my system

**Comment by thelazt16** [comment]
Glad you solved it.
